// All records belong to a fresh, non-persistent browser context. Never attaches
// to a real browser profile or clears an existing library.
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.JAZZ4ALL_URL || 'http://127.0.0.1:8001';
assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname));
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE });
  const context = await browser.newContext({ viewport: { width: 393, height: 851 }, colorScheme: 'light' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.setDefaultTimeout(8000);
  const shown = (selector) => page.locator(selector).first().waitFor({ state: 'visible' });
  const hidden = (selector) => page.locator(selector).waitFor({ state: 'hidden' });
  const songs = () => page.evaluate(async () => (await import('/src/storage.js')).listSongs());
  const source = '[AABA]\n|: Dm7 G7 | Cmaj7/E :| % | F#dim7\n[Bridge]\n[3/4] Bø7 | E7alt | [12/8] Am6/9 | %';
  try {
    await page.goto(base);
    await shown('#empty-state');
    assert.equal((await songs()).length, 0);
    const folder = await page.evaluate(async () => {
      const s = await import('/src/storage.js');
      const folder = await s.createFolder('Originals');
      const lib = await import('/src/library.js');
      await lib.refresh(); lib.showFolder(folder.id);
      return folder.id;
    });
    await page.locator('#btn-new-chart-empty').click();
    await page.locator('#btn-editor-save').click();
    assert.match(await page.locator('#editor-error').textContent(), /title/);
    await page.locator('#editor-title').fill('Evening study');
    await page.locator('#editor-chords').fill('Dm7 | nonsense');
    await page.locator('#btn-editor-save').click();
    assert.match(await page.locator('#editor-error').textContent(), /Line 1, bar 2/);
    assert.equal((await songs()).length, 0);
    // Shortcuts insert at the caret, including touch-friendly accidentals.
    await page.locator('#editor-chords').fill('B');
    await page.locator('#editor-chords').press('End');
    await page.locator('[data-chord-insert="b"]').click();
    await page.locator('[data-chord-insert=" | "]').click();
    await page.locator('[data-chord-insert="%"]').click();
    assert.equal(await page.locator('#editor-chords').inputValue(), 'Bb | %');
    assert.equal(await page.locator('#editor-meter-top').inputValue(), '4');
    assert.equal(await page.locator('#editor-meter-bottom').inputValue(), '4');
    await page.locator('#editor-meter-top').press('ArrowUp');
    assert.equal(await page.locator('#editor-meter-top').inputValue(), '5');
    await page.locator('#editor-meter-top').press('ArrowDown');
    await page.locator('#editor-chords').fill('C | G7 | Am | F');
    await page.locator('#editor-chords').evaluate((e) => e.setSelectionRange(4, 6));
    await page.locator('#editor-structure summary').click();
    await page.locator('#editor-section-name').fill('AABA');
    await page.locator('#btn-insert-section').click();
    assert.match(await page.locator('#editor-chords').inputValue(), /\[AABA\]\s+G7/);
    await page.locator('#editor-bar-meter-top').fill('11');
    await page.locator('#editor-bar-meter-bottom').fill('16');
    await page.locator('#btn-insert-meter').click();
    assert.match(await page.locator('#editor-chords').inputValue(), /\[11\/16\]/);
    await page.locator('#btn-repeat-bars').click();
    assert.match(await page.locator('#editor-chords').inputValue(), /:\s+\[11\/16\].*G7\s+:/);
    assert.equal(await page.locator('#editor-error').textContent(), '');
    await page.locator('#editor-structure summary').click();
    await page.locator('#editor-chords').fill(source);
    for (const width of [320, 393, 768, 1440]) {
      await page.setViewportSize({ width, height: 851 });
      assert.equal(await page.evaluate(() => {
        const d = document.getElementById('chart-editor');
        return d.scrollWidth <= d.clientWidth && d.getBoundingClientRect().left >= 0;
      }), true, `Editor fits at ${width}px`);
    }
    await page.screenshot({ path: '/tmp/jazz4all-editor-desktop.png' });
    await page.setViewportSize({ width: 393, height: 851 });
    await page.locator('[data-editor-view="preview"]').click();
    await shown('#editor-preview-chords irr-chord');
    assert.deepEqual(await page.locator('#editor-preview-chords irr-section').allTextContents(), ['AABA', 'Bridge']);
    assert.deepEqual(await page.locator('#editor-preview-chords .authored-meter').allTextContents(), ['44', '34', '128']);
    await page.screenshot({ path: '/tmp/jazz4all-editor-preview.png' });
    await page.locator('[data-editor-view="write"]').click();
    assert.equal(await page.locator('#editor-chords').inputValue(), source);
    await page.screenshot({ path: '/tmp/jazz4all-editor-mobile.png' });
    // Switching tabs or Android Back preserves the draft; Discard guards it.
    await page.locator('#tab-create').focus();
    await page.locator('#tab-create').press('Home');
    assert.equal(await page.locator('#tab-library').getAttribute('aria-selected'), 'true');
    await page.locator('#tab-library').press('End');
    assert.equal(await page.locator('#tab-create').getAttribute('aria-selected'), 'true');
    await page.evaluate(() => window.jazz4allBack());
    await hidden('#chart-editor');
    await page.locator('#tab-create').click();
    page.once('dialog', (dialog) => dialog.dismiss());
    await page.locator('#btn-editor-close').click();
    await shown('#chart-editor');
    assert.equal(await page.locator('#editor-chords').inputValue(), source);
    await page.locator('#btn-editor-save').click();
    await shown('#destination-dialog');
    assert.equal(await page.locator('#destination-path [aria-current]').textContent(), 'Originals');
    assert.equal((await songs()).length, 0);
    await page.locator('#destination-dialog button[value="cancel"]').click();
    await hidden('#destination-dialog');
    assert.equal(await page.locator('#editor-chords').inputValue(), source);
    await page.locator('#btn-editor-save').click();
    await page.locator('#btn-destination-confirm').click();
    await hidden('#chart-editor');
    await shown('#chart-container irr-chord');
    const created = (await songs())[0];
    assert.equal(created.chartSource.text, source);
    assert.equal(created.chartSource.meter, '4/4');
    assert.deepEqual(created.folderIds, [folder]);
    const before = await page.locator('#chart-container').textContent();
    await page.locator('#btn-chart-tools').click();
    assert.equal(await page.locator('#chart-tools-dialog').evaluate((e) => getComputedStyle(e, '::backdrop').backdropFilter), 'none');
    await page.locator('#btn-transpose-up').click();
    assert.notEqual(await page.locator('#chart-container').textContent(), before);
    assert.equal(await page.locator('#chart-key').textContent(), 'Db');
    await page.screenshot({ path: '/tmp/jazz4all-settings-clear.png' });
    await page.getByRole('button', { name: 'Back to chart', exact: true }).click();
    // Updating a chart keeps the ID and all folder memberships.
    const other = await page.evaluate(async (id) => {
      const s = await import('/src/storage.js');
      const folder = await s.createFolder('Set list');
      await s.fileSongs([id], folder.id, 'add');
      await (await import('/src/library.js')).refresh();
      return folder.id;
    }, created.id);
    await page.locator('#btn-library').click();
    await page.getByRole('button', { name: 'Edit chart Evening study', exact: true }).click();
    assert.equal(await page.locator('#editor-chords').inputValue(), source);
    await page.locator('#editor-title').fill('Revised study');
    await page.locator('#editor-key').selectOption('A-');
    await page.locator('#editor-meter-top').fill('11');
    await page.locator('#editor-meter-bottom').fill('16');
    await page.locator('#editor-chords').fill('Am7 | Dm7 | E7b9 | Am6');
    await page.locator('#btn-editor-save').click();
    await hidden('#chart-editor');
    await page.waitForFunction(() => document.getElementById('chart-title').textContent === 'Revised study');
    assert.equal((await songs()).length, 1);
    assert.equal((await songs())[0].id, created.id);
    assert.deepEqual(new Set((await songs())[0].folderIds), new Set([folder, other]));
    // The editor, saved text and rendered chart all remain available offline.
    await page.evaluate(() => navigator.serviceWorker.ready);
    await context.setOffline(true);
    await page.reload();
    await shown('#chart-container irr-chord');
    assert.equal(await page.locator('#chart-key').textContent(), 'Am');
    await page.locator('#btn-library').click();
    await page.getByRole('button', { name: 'Edit chart Revised study', exact: true }).click();
    assert.equal(await page.locator('#editor-chords').inputValue(), 'Am7 | Dm7 | E7b9 | Am6');
    assert.equal(await page.locator('#editor-meter-top').inputValue(), '11');
    assert.equal(await page.locator('#editor-meter-bottom').inputValue(), '16');
    assert.equal((await songs())[0].chartSource.meter, '11/16');
    await page.locator('#btn-editor-close').click();
    await page.locator('#tab-create').click();
    await page.locator('#editor-title').fill('Discarded fixture');
    await page.locator('#editor-chords').fill('C');
    page.once('dialog', (dialog) => dialog.accept());
    await page.locator('#btn-editor-close').click();
    await hidden('#chart-editor');
    assert.equal((await songs()).length, 1);
    assert.deepEqual(errors, []);
    console.log('PASS: Create tab, retained drafts, named sections, mixed meters, repeat controls, validation, preview, discard guards, folder selection, create/edit persistence, transposition without blur and offline editing.');
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
