import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
const messages = [], timers = new Map(), listeners = new Map();
let sequence = 0;
const window = { jazz4allHost: { postMessage: (text) => messages.push(JSON.parse(text)) }, addEventListener: (type, cb) => listeners.set(type, cb) };
vm.runInNewContext(readFileSync(new URL('../../src/native.js', import.meta.url), 'utf8'), { window, setTimeout(cb) { timers.set(++sequence, cb); return sequence; }, clearTimeout: (id) => timers.delete(id) });
const bridge = window.jazz4allNative;
const answer = (id, rest) => window.jazz4allHost.onmessage({ data: JSON.stringify({ id, ...rest }) });
bridge.setAppearance('dark'); bridge.setReadingMode(true);
assert.deepEqual(messages.splice(0), [{ type: 'appearance', value: 'dark' }, { type: 'reading', value: true }]);
let request = bridge.fetchPlaylist('catalog-id');
assert.deepEqual(messages.at(-1), { type: 'download', id: 'download_1', source: 'catalog-id' });
await assert.rejects(bridge.fetchPlaylist('second'), /already in progress/);
window.jazz4allHost.onmessage({ data: 'malformed' });
answer('unknown', { value: 'ignored' });
answer('download_1', { value: 'irealb://fixture' });
assert.equal(await request, 'irealb://fixture'); assert.equal(timers.size, 0);
const controller = new AbortController();
request = bridge.fetchPlaylist('catalog-id', controller.signal);
const rejection = assert.rejects(request, /cancelled/);
controller.abort(); await rejection;
assert.deepEqual(messages.at(-1), { type: 'cancel', id: 'download_2' }); assert.equal(timers.size, 0);
answer('download_2', { value: 'late response' });
await assert.rejects(bridge.fetchPlaylist('catalog-id', controller.signal), /cancelled/);
request = bridge.fetchPlaylist('catalog-id');
const timedOut = assert.rejects(request, /timed out/);
[...timers.values()][0](); await timedOut;
assert.equal(messages.at(-1).type, 'cancel'); assert.equal(timers.size, 0);
request = bridge.fetchPlaylist('catalog-id');
const gone = assert.rejects(request, /cancelled/); listeners.get('pagehide')(); await gone;
request = bridge.fetchPlaylist('catalog-id');
answer(messages.at(-1).id, { error: 'Unknown catalog entry.' });
await assert.rejects(request, /Unknown catalog/);
request = bridge.savePlaylist('Study.html', '<html>étude</html>');
const exportId = messages.at(-1).id;
assert.deepEqual(messages.at(-1), { type: 'savePlaylist', id: exportId, filename: 'Study.html', text: '<html>étude</html>' });
await assert.rejects(bridge.savePlaylist('Second.html', ''), /already in progress/);
assert.equal(timers.size, 0); // The user may take as long as needed in the save picker.
answer(exportId, { value: 'saved' }); assert.equal(await request, 'saved');
request = bridge.savePlaylist('Study.html', 'content');
answer(messages.at(-1).id, { value: 'cancelled' }); assert.equal(await request, 'cancelled');
request = bridge.savePlaylist('Study.html', 'content');
answer(messages.at(-1).id, { error: 'Could not save' }); await assert.rejects(request, /Could not save/);
request = bridge.savePlaylist('Study.html', 'content');
listeners.get('pagehide')(); assert.equal(await request, 'cancelled');
window.jazz4allHost.postMessage = () => { throw new Error('Closed'); };
await assert.rejects(bridge.savePlaylist('Study.html', 'content'), /save window/);
await assert.rejects(bridge.fetchPlaylist('catalog-id'), /unavailable/); assert.equal(timers.size, 0);
console.log('PASS: asynchronous native replies, catalog IDs, single-flight requests, cancellation, stale/malformed replies, timeout, page teardown and closed transport.');
